# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe
CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\cl.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\cl.exe
AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\ml64.exe

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\link.exe
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\link.exe
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\link.exe


inferay_CXXFLAGS=-nologo -O2 -fp:fast -std:c++20 /EHsc -DNDEBUG
inferay_CXXFLAGS=-nologo -O2 -fp:fast -std:c++20 /EHsc -DNDEBUG
inferay_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 /opt:ref /opt:icf

default:  inferay

all:  inferay

.PHONY: default all  inferay

inferay: build\windows\x64\release\inferay.exe
build\windows\x64\release\inferay.exe: build\.objs\inferay\windows\x64\release\src\main.cpp.obj
	@echo linking.release inferay.exe
	-@mkdir build\windows\x64\release > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe" $(inferay_LDFLAGS) -out:build\windows\x64\release\inferay.exe build\.objs\inferay\windows\x64\release\src\main.cpp.obj

build\.objs\inferay\windows\x64\release\src\main.cpp.obj: src\main.cpp
	@echo compiling.release src\main.cpp
	-@mkdir build\.objs\inferay\windows\x64\release\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\cl.exe" -c $(inferay_CXXFLAGS) -Fobuild\.objs\inferay\windows\x64\release\src\main.cpp.obj src\main.cpp

clean:  clean_inferay

clean_inferay: 
	@del /F /Q build\windows\x64\release\inferay.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\inferay.exe > NUL 2>&1
	@del /F /Q build\windows\x64\release\inferay.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\release\inferay.pdb > NUL 2>&1
	@del /F /Q build\.objs\inferay\windows\x64\release\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\inferay\windows\x64\release\src\main.cpp.obj > NUL 2>&1

